<?php
/**
 * Kukusa CMS
 *
 * Copyright (c) 2020, CodeUP.
 * @author  Upik Saleh <upik@codeup.id>
 */

namespace Kukusa\ModelRepo\Actions;


class UpdateAction extends FormAction
{
    public $type = self::FORM_TYPE_UPDATE;

    public function run($id)
    {
        echo $id;exit;
//        return parent::run(); // TODO: Change the autogenerated stub
    }
}